#install.packages('bibtex', repos = "http://cran.us.r-project.org")
#install.packages("handlr", repos = "http://cran.us.r-project.org")
#library("handlr")
#library("bibtex")
args = commandArgs(trailingOnly=TRUE)
#x <- HandlrClient$new(args[1])
#y <- x$read("bibtex")
#z <- x$write("citeproc")
#cat(z,file=args[2],sep="\n")

install.packages("bib2df", repos = "http://cran.us.r-project.org")
library(bib2df)
library(jsonlite)
df <- bib2df(args[1])
j <- toJSON(df)
cat(j,file=args[2],sep="\n")